# Generated by Django 5.0 on 2026-03-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPECO', '0002_contractuel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur'), ('ENTREPRISE', 'Entreprise'), ('MANAGER', 'Manager'), ('EMPLOYE', 'Employé'), ('DRH', 'Directeur des Ressources Humaines'), ('RH', 'Responsable RH')], default='EMPLOYE', max_length=15),
        ),
    ]
