# Generated by Django 5.0 on 2026-03-04 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPECO', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Raison sociale')),
                ('sigle', models.CharField(blank=True, max_length=30, verbose_name='Sigle / Abréviation')),
                ('secteur', models.CharField(choices=[('SECURITE', 'Sécurité / Gardiennage'), ('BTP', 'BTP / Construction'), ('COMMERCE', 'Commerce'), ('INDUSTRIE', 'Industrie'), ('SERVICES', 'Services'), ('INFORMATIQUE', 'Informatique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='contractuel',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractuels', to='SYGEPECO.entreprise', verbose_name='Entreprise'),
        ),
    ]
