# Generated by Django 6.0.3 on 2026-03-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPECO', '0004_entreprise_contractuel_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestionnaires', to='SYGEPECO.entreprise', verbose_name='Entreprise gérée'),
        ),
    ]
