# Generated by Django 5.0 on 2026-03-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPECO', '0005_userprofile_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractuel',
            name='commune',
            field=models.CharField(blank=True, max_length=100, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='contractuel',
            name='nombre_enfants',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants"),
        ),
        migrations.AddField(
            model_name='contractuel',
            name='numero_cnps',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numéro CNPS'),
        ),
        migrations.AddField(
            model_name='contractuel',
            name='situation_famille',
            field=models.CharField(blank=True, choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf / Veuve'), ('UNION_LIBRE', 'Union libre')], max_length=15, verbose_name='Situation familiale'),
        ),
        migrations.AddField(
            model_name='contractuel',
            name='ville',
            field=models.CharField(blank=True, default='ABIDJAN', max_length=100, verbose_name='Ville'),
        ),
    ]
