# Generated by Django 5.0 on 2026-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPECO', '0006_contractuel_commune_contractuel_nombre_enfants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='document_medical',
            field=models.FileField(blank=True, null=True, upload_to='conges/documents/', verbose_name='Document médical (arrêt maladie)'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=[('ANNUEL', 'Congé annuel'), ('MALADIE', 'Congé maladie'), ('MATERNITE', 'Congé maternité'), ('PATERNITE', 'Congé paternité')], max_length=15),
        ),
    ]
