# Generated by Django 5.0 on 2026-03-09 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPECO', '0011_rename_departement_to_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['nom'], 'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.AlterField(
            model_name='contractuel',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='direction',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions_gerees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poste',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes', to='SYGEPECO.direction'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='SYGEPECO.direction', verbose_name='Direction'),
        ),
    ]
