# Generated by Django 5.0 on 2026-03-10 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPECO', '0012_poste_direction_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='date_debut',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE_MANAGER', 'Validé par le manager'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='contractuel',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], db_index=True, default='ACTIF', max_length=10),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié'), ('RENOUVELE', 'Renouvelé')], db_index=True, default='EN_COURS', max_length=10),
        ),
        migrations.AlterField(
            model_name='permission',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], db_index=True, default='EN_ATTENTE', max_length=12),
        ),
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
