# Generated by Django 5.0 on 2026-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPECO', '0013_alter_conge_date_debut_alter_conge_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_debut',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='date_debut',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard'), ('JUSTIFIE', 'Absence justifiée'), ('CONGE', 'En congé'), ('PERMISSION', 'En permission')], db_index=True, default='PRESENT', max_length=12),
        ),
    ]
