# Generated by Django 5.0 on 2026-03-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYGEPECO', '0014_db_indexes_contrat_permission_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractuel',
            name='document_prise_service',
            field=models.FileField(blank=True, null=True, upload_to='contractuels/prise_service/', verbose_name='Document de prise de service'),
        ),
        migrations.AddField(
            model_name='contractuel',
            name='numero_piece_identite',
            field=models.CharField(blank=True, max_length=30, verbose_name="Numéro de la pièce d'identité"),
        ),
        migrations.AddField(
            model_name='contractuel',
            name='piece_identite_recto',
            field=models.ImageField(blank=True, null=True, upload_to='contractuels/cni/', verbose_name="Carte d'identité (recto)"),
        ),
        migrations.AddField(
            model_name='contractuel',
            name='piece_identite_verso',
            field=models.ImageField(blank=True, null=True, upload_to='contractuels/cni/', verbose_name="Carte d'identité (verso)"),
        ),
        migrations.AddField(
            model_name='contractuel',
            name='urgence_lien',
            field=models.CharField(blank=True, choices=[('CONJOINT', 'Conjoint(e)'), ('PARENT', 'Parent (père / mère)'), ('FRERE_SOEUR', 'Frère / Sœur'), ('AMI', 'Ami(e)'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Lien'),
        ),
        migrations.AddField(
            model_name='contractuel',
            name='urgence_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Personne à contacter (nom)'),
        ),
        migrations.AddField(
            model_name='contractuel',
            name='urgence_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence"),
        ),
    ]
